# Generated by Django 3.0.5 on 2020-04-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='file_url',
            field=models.URLField(blank=True, default='', max_length=2083),
        ),
    ]
